---
image_resource:
  type: docker-image
  source:
      repository: tscolari/garden-lite-ci

platform: linux

inputs:
  - name: garden-lite-git
  - name: garden-runc-release

params:
  VERSION_PATH:
  GARDEN_RELEASE_PATH:
  VAGRANT_CLOUD_ACCESS_KEY:

run:
  path: garden-lite-git/ci/scripts/build.sh
